# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build_And_Test_MacOS:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
            lfs: true
      
      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
            git lfs checkout

            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew install glog
            brew install java
            brew install wget
            
            wget https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-macos.zip
            
            mkdir -p third_party/llvm-10.0.0-m1
            mv taichi-llvm-10.0.0-macos.zip third_party/llvm-10.0.0-m1
            cd third_party/llvm-10.0.0-m1 && tar -xf taichi-llvm-10.0.0-macos.zip && cd ../..

      - name: Build
        run: |
            mkdir -p build
            cd build && cmake .. && make -j && cd ..

      - name: Test
        run: ./build/tests/InheritanceUnitTests/ComplexCallMethodTest/complex_call_method_test
  
  Build_And_Test_Linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
            lfs: true
      
      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
            git lfs checkout
            
            sudo apt-get update
            sudo apt-get install libgoogle-glog-dev
            sudo apt-get install default-jre
            
            wget https://github.com/jim19930609/Jack2LLVM/releases/download/llvm/taichi-llvm-10.0.0-linux.zip
            tar -xf taichi-llvm-10.0.0-linux.zip && mv taichi-llvm-10.0.0-linux third_party/

      - name: Build
        run: |
            mkdir -p build
            cd build && cmake .. && make -j && cd ..

      - name: Test
        run: ./build/tests/InheritanceUnitTests/ComplexCallMethodTest/complex_call_method_test
